s: 
	make -f Makefile.ser Garli0.952

p:
	@echo '****Sorry, parallel compilation for version 0.95 is not yet available. ****'
	@echo '****When it has been fully tested it will be made available.  Check the website soon. ****'

clean:
	rm -f *.o Garli0.952*

