#!/bin/bash

$1 $2 -t 01.GTR.conf | tee RUNOUTPUT.log
$1 $2 -t 02.GTRIG.conf | tee -a RUNOUTPUT.log
$1 $2 -t 03.GTRIG3.conf | tee -a RUNOUTPUT.log
$1 $2 -t 04.GTRF3.conf | tee -a RUNOUTPUT.log
$1 $2 -t 05.GTR.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 06.GTRIG.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 07.GTRIG3.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 08.GTRF3.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 11.wagempI.conf | tee -a RUNOUTPUT.log
$1 $2 -t 12.wagempIG.conf | tee -a RUNOUTPUT.log
$1 $2 -t 13.wagempG3.conf | tee -a RUNOUTPUT.log
$1 $2 -t 14.wagempF3.conf | tee -a RUNOUTPUT.log
$1 $2 -t 15.wagempI.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 16.wagempIG.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 17.wagempG3.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 18.wagempF3.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 21.OK2Pf3x4.conf | tee -a RUNOUTPUT.log
$1 $2 -t 22.M3x4K2Pemp.conf | tee -a RUNOUTPUT.log
$1 $2 -t 23.M3K2Pemp.conf | tee -a RUNOUTPUT.log
$1 $2 -t 25.OK2Pf3x4.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 26.M3x4K2Pemp.boot.conf | tee -a RUNOUTPUT.log
$1 $2 -t 27.M3K2Pemp.boot.conf | tee -a RUNOUTPUT.log
