#!/bin/bash

$1 $2 09.GTR.conf  |tee RUNOUTPUT.log
$1 $2 13.HKYG.conf |tee -a RUNOUTPUT.log
$1 $2 20.REVIG.conf |tee -a RUNOUTPUT.log
$1 $2 23.F81I.conf |tee -a RUNOUTPUT.log
$1 $2 33.GTRF.conf |tee -a RUNOUTPUT.log
$1 $2 34.GTRG5.conf |tee -a RUNOUTPUT.log
