s: 
	make -f Makefile.ser Garli0.96b6.r226

p:
	@echo '****Sorry, parallel compilation for version 0.96 is not yet available. ****'
	@echo '****When it has been fully tested it will be made available. ****'

clean:
	rm -f *.o Garli*

