
#NOTE - this is from the poor make system of version 0.951 and earlier.  The configure
#	script mechanism should now be used instead if possible

s: 
	make -f Makefile.ser Garli0.96b8

p:
	@echo '****Sorry, parallel compilation for version 0.96 is not yet available. ****'
	@echo '****When it has been fully tested it will be made available. ****'

clean:
	rm -f *.o Garli*

