#!/bin/bash
$1 $2 -t 01.36pos.conf | tee RUNOUTPUT.log 
$1 $2 -t 02.36neg.conf | tee -a RUNOUTPUT.log
$1 $2 -t 03.36posBack.conf | tee -a RUNOUTPUT.log
$1 $2 -t 04.36negBack.conf | tee -a RUNOUTPUT.log
$1 $2 -t 05.36pos.step.conf | tee -a RUNOUTPUT.log
$1 $2 -t 06.36neg.step.conf | tee -a RUNOUTPUT.log
$1 $2 -t 07.36posBack.step.conf | tee -a RUNOUTPUT.log
$1 $2 -t 08.36negBack.step.conf | tee -a RUNOUTPUT.log
